export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const MODIFY_BALANCE = 'MODIFY_BALANCE';
export const RESET_BALANCE = 'RESET_BALANCE';
